<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pc106426" name="com.gateside.autotesting.generation.unittest.AllGamesTestCase" tests="2" failures="1" timestamp="8 Sep 2015 03:19:55 GMT" time="1.047" errors="0">
  <testcase name="Test02AllGames" time="0.172" classname="com.gateside.autotesting.generation.unittest.AllGamesTestCase">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.gateside.autotesting.Gat.executor.CaseExecutor.invokeMethod(CaseExecutor.java:66)
	at com.gateside.autotesting.Gat.executor.InterfaceStepsExecutor.executeCase(InterfaceStepsExecutor.java:30)
	at com.gateside.autotesting.Gat.executor.CaseExecutor.execute(CaseExecutor.java:33)
	at com.gateside.autotesting.generation.unittest.AllGamesTestCase.Test02AllGames(AllGamesTestCase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: net.sf.json.JSONException: JSONObject["result"] is not a JSONObject.
	at net.sf.json.JSONObject.getJSONObject(JSONObject.java:2058)
	at com.wanmei.mobile.iat.main.steps.LoginSteps.loginLink(LoginSteps.java:26)
	... 32 more
]]>
    </failure>
  </testcase> <!-- Test02AllGames -->
  <testcase name="Test01AllGames" time="0.875" classname="com.gateside.autotesting.generation.unittest.AllGamesTestCase"/>
</testsuite> <!-- com.gateside.autotesting.generation.unittest.AllGamesTestCase -->
